### ISSUE TITLE
npm@3 compatibility

### ISSUE THREAD

**Issue by Globegitter** [stealjs/system-npm#72]
It seems that this plugin is not yet compatible with the upcoming npm 3.x and its flat file structure.

**Comment by matthewp** [comment]
Thanks!  I was wondering about this.  Probably need to prioritize this to be fixed before the official npm 3 release.

**Comment by matthewp** [comment]
Hey @Globegitter, do you know more about the flat file structure?  Do you have a link to the article (i can't seem to find it).  It's unclear to me what exactly changed, but hopefully it didn't change in a way that will prevent us from finding the correct deps.

**Comment by Globegitter** [comment]
@matthewp here is an article http://blog.npmjs.org/post/122450408965/npm-weekly-20-npm-3-is-here-ish which links to https://github.com/npm/npm/releases/tag/v3.0.0, which seems to have the best description so far I have found.

**Comment by BigAB** [comment]
Just to add urgency to this issue the node v5 release candidate comes with npm 3 installed by default
https://github.com/nodejs/node/releases/tag/v5.0.0-rc.1

**Comment by matthewp** [comment]
This is probably the first post-donejs release item I'll do.

**Comment by matthewp** [comment]
I looked a little into this. I think we're going to have to have an opt-in.  Probably by setting something like `"npmVersion": 3` or something in config.  Otherwise we won't be able to detect to use this different algorithm.

Otherwise I think it's probably not a hard change. The hardest part will be figuring out when nesting does happen because there is very little documentation on how it works.

**Comment by matthewp** [comment]
This is in the latest.
